### ISSUE TITLE
add GLTF/GLB exporter

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/PointCloudConverter#39]
currently testing this, comment here if you have ideas/requirements. (converting LAS/LAZ files to GLB)

### TODO
- [x] gltf writer as separate dll "plugin"
- [x] convert single cloud file to gltf/glb
- [x] convert batch/folder of laz files to multiple gltf files (1 cloud > 1 glb)
- [x] split single laz cloud into multiple gltf files (by gridsize)
- [x] split multiple laz clouds into multiple gltf files (by gridsize)
- [x] split multiple laz clouds into multiple gltf files (by gridsize) AND export .pcroot or similar header file
- [x] add threading support
- [x] add logging support
- [x] add support for all features: scale, skip, keep, flip, offset..
- [x] create store page
- [x] tutorial guide
- [x] tutorial video * https://www.youtube.com/watch?v=K9sPYtoOEz8
- [x] Release plugin beta: Current idea: It is paid plugin, if you already own point cloud viewer then its 50% discount
- [ ] v3 viewer: add support for glb tile data *probably needs separate V3 viewer, if want to run in webgl also)
- [ ] simplified UI version for GLTF converter or separate converter?

**Comment by unitycoder** [comment]
initial version is available
https://github.com/unitycoder/PointCloudConverter/wiki/GLTF-GLB-Exporter
